// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.1;

enum HomeAway {
    None,
    HomeTeam,
    AwayTeam
}

enum MatchStatus {
    STATUS_NONE,
    STATUS_CANCELED,
    STATUS_DELAYED,
    STATUS_END_OF_FIGHT,
    STATUS_END_OF_ROUND,
    STATUS_END_PERIOD,
    STATUS_FIGHTERS_INTRODUCTION,
    STATUS_FIGHTERS_WALKING,
    STATUS_FINAL,
    STATUS_FINAL_PEN,
    STATUS_FIRST_HALF,
    STATUS_FULL_TIME,
    STATUS_HALFTIME,
    STATUS_IN_PROGRESS,
    STATUS_IN_PROGRESS_2,
    STATUS_POSTPONED,
    STATUS_PRE_FIGHT,
    STATUS_RAIN_DELAY,
    STATUS_SCHEDULED,
    STATUS_SECOND_HALF,
    STATUS_TBD,
    STATUS_UNCONTESTED,
    STATUS_ABANDONED,
    STATUS_FORFEIT
}
